name: SqlServer Build & Release

on:
  push:
    tags:
      - 'SqlServer/v[0-9]+.[0-9]+.[0-9]+'
      - 'SqlServer/v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
    branches: [ '*/main' ]
  pull_request:
    branches: [ '*/main' ]

env:
  PKG_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || null }}
  DOTNET_VERSION: 9.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set version
      if: ${{ !env.PKG_VERSION }}
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "PKG_VERSION=0.0.0-preview.${{github.run_number}}.$calculatedSha" >> $GITHUB_ENV
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Build project
      run: dotnet build src/Aspire.SqlServer/
           -c Release
           /p:ContinuousIntegrationBuild=true
           /p:Version=${PKG_VERSION#SqlServer/v}

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        if-no-files-found: error
        path: |
          **/*.nupkg
          **/*.snupkg

  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [build]
    steps:

    - name: Download artifact from build
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - name: Push to NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json